name: Build Android

on:
  push:
    branches: [ main, feature/engagement-service-skeleton ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.38.6'
        channel: 'stable'
        cache: true

    - name: Reset generated Flutter state
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Build Android Release APK
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4096m -XX:MaxMetaspaceSize=1024m'"
      run: flutter build apk --release --split-per-abi

    - name: Archive Android Release APKs
      uses: actions/upload-artifact@v4
      with:
        name: necxa-android-release-apks
        path: build/app/outputs/flutter-apk/
        retention-days: 30
